### ISSUE TITLE
Fetch account balances

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#1]

**Comment by listenaddress** [comment]
We'll need to adjust redux store to store balances of each account in array.

**Comment by Schwartz10** [comment]
Hey just wanted to leave you with some more helpful information to get you started on this too in case you haven't already. Also have an idea of how to keep the redux store in a good "state" no pun intended lol.

Redux store currently has an array of accounts, a selectedAccount, and a single `balance` key that represents the balance of the selected account:

```
export const initialState = {
  accounts: [], // array of strings that are filecoin addresses
  selectedAccount: '',
  error: null,
  balance: new BigNumber(0)
}
```

Like you recommended, let's swap the array of strings for an array of objects that looks like this:

```
[
 { address: 't1xxx', balance: <BigNumber> },
 { address: 't1yyy', balance: <BigNumber> }
]
```

Instead of storing a string that's an address for `selectedAccount`, let's change `selectedAccount` to actually be an index that points to the `accounts` array. I think this will make our lives muuuch easier throughout other areas of the app and the app overall much more performant. So redux at any point in time would look like this:

```
{
  accounts: [{ address: 't1yyy', balance: <BigNumber> }]
  selectedAccount: 0, // a pointer to the accounts array index
}
```

Then we need to tweak a few other small things in order for this to happen:

remove `balance` from initial state because that field is no longer needed on its own.

`updateBalance` in store/actions.js -> should take a balance, and an index of what account to update (should also be pretty straight forward). The `accountIndex` should be included in the payload along with the balance.

`updateBalance` in store/states.js -> should take a balance, and an index of what account to update. Should update the balance _inside_ the array of accounts at that index. 
(ie:
```js
export const updateBalance = (state, {balance, accountIndex}) => ({
  ...state,
  accounts[accountIndex].balance = balance // watch out for weird mutation bugs?
})
```

`useFilecoin` hook - will need to change the calls to `updateBalance` to include the account index. 

`useAccounts` hook - will need to recalculate `selectedAccount` by using the `accountIndex` field and grabbing that index in the `accounts` array from redux.

`useBalance` hook - should now take an accountIndex and return the balance associated with that account (could be 0 index by default).

Then i think that should be it!
