### ISSUE TITLE
"Equivalent" icon in funds input looks like button

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#146]
I did a pseudo UX interview with a friend (who is a web3 engineer and has experience with wallets) - he was confused at the equivalent icon in the funds input. He thought it was a button to "flip" the inputs. Maybe we make the color less pronounced and instead worked into the background?

![image](https://user-images.githubusercontent.com/12353734/75684604-21ff7c80-5c67-11ea-8d8e-fe38bc57439d.png)

**Comment by as-dr** [comment]
Yeah I also think it's confusing, because not many people have experience with this symbol. An easier symbol would just be to use an equals sign `=`

**Comment by as-dr** [comment]
Yeah I also think it's confusing, because not many people have experience with this symbol. 

An easier symbol would just be to use an equals sign `=` 

Can also reduce the `borderWidth` and....

![image](https://user-images.githubusercontent.com/6787950/75693950-867e0400-5c86-11ea-8958-ef8a24fd8c98.png)
