### ISSUE TITLE
Funds Input sets to 0 on :active after inputting number

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#206]
# Problem

1. I input an amount of FIL I want to send into the `Funds` input
1. The corresponding USD amount is displayed
1. *IF* I click on the USD input, the FIL input displays `0`
1. *IF* I then click on the FIL input, the USD displays `0`

## Why is this a problem?
It is a little confusing to see the number revert to `0` just on triggering `Funds` input's `:active` state. 

## Proposed Solution
Instead of displaying `0` how about we display the previously inputted amount, but add a new `:active` state design to indicate it can be edited?

## Reference
![image](https://user-images.githubusercontent.com/6787950/76433884-b7032380-6393-11ea-9ac3-62ca6173e208.png)

**Comment by Schwartz10** [comment]
@as-dr can we try and do less instead of more here? What if we just change the input number to 0 when the user starts typing in the opposite box instead of just focusing in it?

That way, if i click on USD after entering filecoin, the filecoin amount will stay until I start typing usd.

I removed the bug label because this is working as expected.

**Comment by as-dr** [comment]
@Schwartz10 Sounds good. 👍
