### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by acostalima** [glifio/wallet#369]
Hi,
We're looking forward to use this wallet but it's unclear what's its current status. Is it working already? Do you offer some sort of SDK?

Thanks!

CC @vasco-santos @hugomrdias

**Comment by Schwartz10** [comment]
Hey @acostalima - i'll plan to update this repo's README answering these Q's. 

We're currently in the process of upgrading to the new Filecoin interop network. We expect to finish the upgrade by the end of next week, at which point the wallet will be fully functional (it already is working quite well, just a few weird inconsistencies while we're upgrading that might make things confusing).

The wallet will get audited in early May. There may be security issues in the current wallet that we are unaware of, esp with non-ledger based wallets. 

If you give me a better sense of how you'd like to use the wallet, or its code, I can give you a better idea of where to look and which modules might be useful to you. All of our modules could use a little bit of love on the documentation side of things, which I'll aim to prioritize in the next week or two. 

Feel free to ping me on the Filecoin slack too with any Q's! Don't hesitate..

**Comment by acostalima** [comment]
@Schwartz10 thanks for the swift reply!
Our plan is to come up with a webapp to store and retrieve files from the Filecoin network and use the wallet to pay the miners.

**Comment by Schwartz10** [comment]
Interesting @acostalima ! Would love to hear more about this, as it's something we've been investigating on our end too.

A few Q's:
- what types of wallets do you want to support? I'm assuming the ones we demonstrate in this web wallet, but want to make sure.
- what is the relationship between your webapp and lotus? Is each user expected to run their own node? Or are you hosting a remote node for the webapp's users to use? Assuming you don't want each user to run their own node because if they were, you could just use the node's wallet.
- How are storage deals being made? Are you running your own client node that's making, monitoring, and paying out deals on behalf of users? Or are you doing something fancy off-chain directly with storage miners?

**Comment by Schwartz10** [comment]
Hey @acostalima i'm closing this issue for now, since we're mainly using issue tracking for bugs and future features. Feel free to ping me on slack or keep writing in this issue with questions. 

It's probably not super helpful without more context, but just in case, this function gets called when we attempt to send filecoin https://github.com/openworklabs/filecoin-web-wallet/blob/primary/components/Wallet/Send.js/index.jsx#L133. The WalletProvider directory handles the core filecoin logic within the application. https://github.com/openworklabs/filecoin-web-wallet/tree/primary/WalletProvider
