### ISSUE TITLE
Use new non-waiting endpoint > statewaitmsg to confirm pending msgs

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#88]
Will check if I'm able to reproduce.

**Comment by listenaddress** [comment]
Yep, got it again. The third time I go to sign a message, it gets really slow. The screen says "Sign the transaction on your Ledger device to confirm." but it takes ~15 seconds for the transaction to show up on my device, and then after signing the transaction on my device, another ~15 seconds for the transaction to show on the browser.

**Comment by listenaddress** [comment]
After refreshing my browser, it works quickly again for a couple transactions.

**Comment by listenaddress** [comment]
It actually takes ~1 minute sometimes. It's not totally consistent. And now it seems only to be the wait between when the screen initially says "Sign the transaction..." and when it shows up on my device. After signing, the tx updates right away.

**Comment by listenaddress** [comment]
It does seem to be working tho.

**Comment by listenaddress** [comment]
Another interesting bit—after a couple slow transactions, it speeds back up.

**Comment by Schwartz10** [comment]
Good find here @listenaddress - this is because the `StateWaitMsg` endpoint on the lotus jsonrpc is blocking. So when we try to submit too many transactions and confirm them all at once, it blocks a future call to get a nonce for an upcoming transaction. 

Hoping we can switch to https://github.com/filecoin-project/lotus/blob/7e0be91cfd44c1664ac18f81080544b1341872f1/node/impl/full/state.go#L287 for message confirmation because it's non blocking

**Comment by Schwartz10** [comment]
https://filecoinproject.slack.com/archives/GRT37S147/p1583440322084600  relative conversation in slack

**Comment by Schwartz10** [comment]
Will fix pending https://github.com/filecoin-project/lotus/issues/1412
